export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE'

export const FLUSH_AUTH_STATE_FROM_STATE = 'FLUSH_AUTH_STATE_FROM_STATE'

export const RESEND_EMAIL_REQUEST = 'RESEND_EMAIL_REQUEST'
export const RESEND_EMAIL_SUCCESS = 'RESEND_EMAIL_SUCCESS'
export const RESEND_EMAIL_FAILURE = 'RESEND_EMAIL_FAILURE'

export const FETCH_NEW_ACCESS_TOKEN_REQUEST = 'FETCH_NEW_ACCESS_TOKEN_REQUEST'
export const FETCH_NEW_ACCESS_TOKEN_SUCCESS = 'FETCH_NEW_ACCESS_TOKEN_SUCCESS'
export const FETCH_NEW_ACCESS_TOKEN_FAILURE = 'FETCH_NEW_ACCESS_TOKEN_FAILURE'
