export const ORGANIZATION_DATA_STEP1 = 'ORGANIZATION_DATA_STEP1'
export const ORGANIZATION_DATA_STEP2 = 'ORGANIZATION_DATA_STEP2'
export const ORGANIZATION_DATA_STEP3 = 'ORGANIZATION_DATA_STEP3'
export const ORGANIZATION_DATA_STEP4 = 'ORGANIZATION_DATA_STEP4'

export const ORGANIZATION_URL_EXIST_REQUEST = 'ORGANIZATION_URL_EXIST_REQUEST'
export const ORGANIZATION_URL_EXIST_SUCCESS = 'ORGANIZATION_URL_EXIST_SUCCESS'
export const ORGANIZATION_URL_EXIST_FAILURE = 'ORGANIZATION_URL_EXIST_FAILURE'

export const ORGANIZATION_CREATION_REQUEST = 'ORGANIZATION_CREATION_REQUEST'
export const ORGANIZATION_CREATION_SUCCESS = 'ORGANIZATION_CREATION_SUCCESS'
export const ORGANIZATION_CREATION_FAILURE = 'ORGANIZATION_CREATION_FAILURE'

export const FLUSH_ORGANIZATION_STATE_FROM_STATE = 'FLUSH_ORGANIZATION_STATE_FROM_STATE'
