export const SIGNUP_REQUEST = 'SIGNUP_REQUEST'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE'

export const FLUSH_USER_ERROR_FROM_STATE = 'FLUSH_USER_ERROR_FROM_STATE'