export default [
    { "value": "", "text": "Select" },
    { "value": "US", "text": "United States", "continent": "North America" },
    { "value": "CA", "text": "Canada", "continent": "North America" },
    { "value": "GB", "text": "United Kingdom", "continent": "Europe" },
    { "value": "AF", "text": "Afghanistan", "continent": "Asia" },
    { "value": "AX", "text": "Åland Islands", "continent": "Europe" },
    { "value": "AL", "text": "Albania", "continent": "Europe" },
    { "value": "DZ", "text": "Algeria", "continent": "Africa" },
    { "value": "AS", "text": "American Samoa", "continent": "Australia" },
    { "value": "AD", "text": "Andorra", "continent": "Europe" },
    { "value": "AO", "text": "Angola", "continent": "Africa" },
    { "value": "AI", "text": "Anguilla", "continent": "North America" },
    { "value": "AQ", "text": "Antarctica", "continent": "Antarctica" },
    { "value": "AG", "text": "Antigua and Barbuda", "continent": "North America" },
    { "value": "AR", "text": "Argentina", "continent": "South America" },
    { "value": "AM", "text": "Armenia", "continent": "Asia" },
    { "value": "AW", "text": "Aruba", "continent": "North America" },
    { "value": "AU", "text": "Australia", "continent": "Australia" },
    { "value": "AT", "text": "Austria", "continent": "Europe" },
    { "value": "AZ", "text": "Azerbaijan", "continent": "Asia" },
    { "value": "BS", "text": "Bahamas", "continent": "North America" },
    { "value": "BH", "text": "Bahrain", "continent": "Asia" },
    { "value": "BD", "text": "Bangladesh", "continent": "Asia" },
    { "value": "BB", "text": "Barbados", "continent": "North America" },
    { "value": "BY", "text": "Belarus", "continent": "Europe" },
    { "value": "BE", "text": "Belgium", "continent": "Europe" },
    { "value": "BZ", "text": "Belize", "continent": "North America" },
    { "value": "BJ", "text": "Benin", "continent": "Africa" },
    { "value": "BM", "text": "Bermuda", "continent": "North America" },
    { "value": "BT", "text": "Bhutan", "continent": "Asia" },
    { "value": "BO", "text": "Bolivia", "continent": "South America" },
    { "value": "BQ", "text": "Bonaire, Sint Eustatius and Saba", "continent": "North America" },
    { "value": "BA", "text": "Bosnia and Herzegovina", "continent": "Europe" },
    { "value": "BW", "text": "Botswana", "continent": "Africa" },
    { "value": "BV", "text": "Bouvet Island", "continent": "Antarctica" },
    { "value": "BR", "text": "Brazil", "continent": "South America" },
    { "value": "IO", "text": "British Indian Ocean Territory", "continent": "Asia" },
    { "value": "BN", "text": "Brunei Darussalam", "continent": "Asia" },
    { "value": "BG", "text": "Bulgaria", "continent": "Europe" },
    { "value": "BF", "text": "Burkina Faso", "continent": "Africa" },
    { "value": "BI", "text": "Burundi", "continent": "Africa" },
    { "value": "KH", "text": "Cambodia", "continent": "Asia" },
    { "value": "CM", "text": "Cameroon", "continent": "Africa" },
    { "value": "CA", "text": "Canada", "continent": "North America" },
    { "value": "CV", "text": "Cape Verde", "continent": "Africa" },
    { "value": "KY", "text": "Cayman Islands", "continent": "North America" },
    { "value": "CF", "text": "Central African Republic", "continent": "Africa" },
    { "value": "TD", "text": "Chad", "continent": "Africa" },
    { "value": "CL", "text": "Chile", "continent": "South America" },
    { "value": "CN", "text": "China", "continent": "Asia" },
    { "value": "CX", "text": "Christmas Island", "continent": "Asia" },
    { "value": "CC", "text": "Cocos (Keeling) Islands", "continent": "Asia" },
    { "value": "CO", "text": "Colombia", "continent": "South America" },
    { "value": "KM", "text": "Comoros", "continent": "Africa" },
    { "value": "CG", "text": "Congo", "continent": "Africa" },
    { "value": "CD", "text": "Congo, The Democratic Republic Of The", "continent": "Africa" },
    { "value": "CK", "text": "Cook Islands", "continent": "Australia" },
    { "value": "CR", "text": "Costa Rica", "continent": "North America" },
    { "value": "HR", "text": "Croatia", "continent": "Europe" },
    { "value": "CU", "text": "Cuba", "continent": "North America" },
    { "value": "CW", "text": "Curaçao", "continent": "North America" },
    { "value": "CY", "text": "Cyprus", "continent": "Asia" },
    { "value": "CZ", "text": "Czech Republic", "continent": "Europe" },
    { "value": "CI", "text": "Côte DIvoire", "continent": "Africa" },
    { "value": "DK", "text": "Denmark", "continent": "Europe" },
    { "value": "DJ", "text": "Djibouti", "continent": "Africa" },
    { "value": "DM", "text": "Dominica", "continent": "North America" },
    { "value": "DO", "text": "Dominican Republic", "continent": "North America" },
    { "value": "EC", "text": "Ecuador", "continent": "South America" },
    { "value": "EG", "text": "Egypt", "continent": "Africa" },
    { "value": "SV", "text": "El Salvador", "continent": "North America" },
    { "value": "GQ", "text": "Equatorial Guinea", "continent": "Africa" },
    { "value": "ER", "text": "Eritrea", "continent": "Africa" },
    { "value": "EE", "text": "Estonia", "continent": "Europe" },
    { "value": "ET", "text": "Ethiopia", "continent": "Africa" },
    { "value": "FK", "text": "Falkland Islands (Malvinas)", "continent": "South America" },
    { "value": "FO", "text": "Faroe Islands", "continent": "Europe" },
    { "value": "FJ", "text": "Fiji", "continent": "Australia" },
    { "value": "FI", "text": "Finland", "continent": "Europe" },
    { "value": "FR", "text": "France", "continent": "Europe" },
    { "value": "GF", "text": "French Guiana", "continent": "South America" },
    { "value": "PF", "text": "French Polynesia", "continent": "Australia" },
    { "value": "TF", "text": "French Southern Territories", "continent": "Antarctica" },
    { "value": "GA", "text": "Gabon", "continent": "Africa" },
    { "value": "GM", "text": "Gambia", "continent": "Africa" },
    { "value": "GE", "text": "Georgia", "continent": "Asia" },
    { "value": "DE", "text": "Germany", "continent": "Europe" },
    { "value": "GH", "text": "Ghana", "continent": "Africa" },
    { "value": "GI", "text": "Gibraltar", "continent": "Europe" },
    { "value": "GR", "text": "Greece", "continent": "Europe" },
    { "value": "GL", "text": "Greenland", "continent": "North America" },
    { "value": "GD", "text": "Grenada", "continent": "North America" },
    { "value": "GP", "text": "Guadeloupe", "continent": "North America" },
    { "value": "GU", "text": "Guam", "continent": "Australia" },
    { "value": "GT", "text": "Guatemala", "continent": "North America" },
    { "value": "GG", "text": "Guernsey", "continent": "Europe" },
    { "value": "GN", "text": "Guinea", "continent": "Africa" },
    { "value": "GW", "text": "Guinea-Bissau", "continent": "Africa" },
    { "value": "GY", "text": "Guyana", "continent": "South America" },
    { "value": "HT", "text": "Haiti", "continent": "North America" },
    { "value": "HM", "text": "Heard and McDonald Islands", "continent": "Antarctica" },
    { "value": "VA", "text": "Holy See (Vatican City State)", "continent": "Europe" },
    { "value": "HN", "text": "Honduras", "continent": "North America" },
    { "value": "HK", "text": "Hong Kong", "continent": "Asia" },
    { "value": "HU", "text": "Hungary", "continent": "Europe" },
    { "value": "IS", "text": "Iceland", "continent": "Europe" },
    { "value": "IN", "text": "India", "continent": "Asia" },
    { "value": "ID", "text": "Indonesia", "continent": "Asia" },
    { "value": "IR", "text": "Iran, Islamic Republic Of", "continent": "Asia" },
    { "value": "IQ", "text": "Iraq", "continent": "Asia" },
    { "value": "IE", "text": "Ireland", "continent": "Europe" },
    { "value": "IM", "text": "Isle of Man", "continent": "Europe" },
    { "value": "IL", "text": "Israel", "continent": "Asia" },
    { "value": "IT", "text": "Italy", "continent": "Europe" },
    { "value": "JM", "text": "Jamaica", "continent": "North America" },
    { "value": "JP", "text": "Japan", "continent": "Asia" },
    { "value": "JE", "text": "Jersey", "continent": "Europe" },
    { "value": "JO", "text": "Jordan", "continent": "Asia" },
    { "value": "KZ", "text": "Kazakhstan", "continent": "Asia" },
    { "value": "KE", "text": "Kenya", "continent": "Africa" },
    { "value": "KI", "text": "Kiribati", "continent": "Australia" },
    { "value": "KP", "text": "Korea, Democratic Peoples Republic Of", "continent": "Asia" },
    { "value": "KR", "text": "Korea, Republic of", "continent": "Asia" },
    { "value": "KW", "text": "Kuwait", "continent": "Asia" },
    { "value": "KG", "text": "Kyrgyzstan", "continent": "Asia" },
    { "value": "LA", "text": "Lao Peoples Democratic Republic", "continent": "Asia" },
    { "value": "LV", "text": "Latvia", "continent": "Europe" },
    { "value": "LB", "text": "Lebanon", "continent": "Asia" },
    { "value": "LS", "text": "Lesotho", "continent": "Africa" },
    { "value": "LR", "text": "Liberia", "continent": "Africa" },
    { "value": "LY", "text": "Libya", "continent": "Africa" },
    { "value": "LI", "text": "Liechtenstein", "continent": "Europe" },
    { "value": "LT", "text": "Lithuania", "continent": "Europe" },
    { "value": "LU", "text": "Luxembourg", "continent": "Europe" },
    { "value": "MO", "text": "Macao", "continent": "Asia" },
    { "value": "MK", "text": "Macedonia, the Former Yugoslav Republic Of", "continent": "Europe" },
    { "value": "MG", "text": "Madagascar", "continent": "Africa" },
    { "value": "MW", "text": "Malawi", "continent": "Africa" },
    { "value": "MY", "text": "Malaysia", "continent": "Asia" },
    { "value": "MV", "text": "Maldives", "continent": "Asia" },
    { "value": "ML", "text": "Mali", "continent": "Africa" },
    { "value": "MT", "text": "Malta", "continent": "Europe" },
    { "value": "MH", "text": "Marshall Islands", "continent": "Australia" },
    { "value": "MQ", "text": "Martinique", "continent": "North America" },
    { "value": "MR", "text": "Mauritania", "continent": "Africa" },
    { "value": "MU", "text": "Mauritius", "continent": "Africa" },
    { "value": "YT", "text": "Mayotte", "continent": "Africa" },
    { "value": "MX", "text": "Mexico", "continent": "North America" },
    { "value": "FM", "text": "Micronesia, Federated States Of", "continent": "Australia" },
    { "value": "MD", "text": "Moldova, Republic of", "continent": "Europe" },
    { "value": "MC", "text": "Monaco", "continent": "Europe" },
    { "value": "MN", "text": "Mongolia", "continent": "Asia" },
    { "value": "ME", "text": "Montenegro", "continent": "Europe" },
    { "value": "MS", "text": "Montserrat", "continent": "North America" },
    { "value": "MA", "text": "Morocco", "continent": "Africa" },
    { "value": "MZ", "text": "Mozambique", "continent": "Africa" },
    { "value": "MM", "text": "Myanmar", "continent": "Asia" },
    { "value": "NA", "text": "Namibia", "continent": "Africa" },
    { "value": "NR", "text": "Nauru", "continent": "Australia" },
    { "value": "NP", "text": "Nepal", "continent": "Asia" },
    { "value": "NL", "text": "Netherlands", "continent": "Europe" },
    { "value": "AN", "text": "Netherlands Antilles", "continent": "North America" },
    { "value": "NC", "text": "New Caledonia", "continent": "Australia" },
    { "value": "NZ", "text": "New Zealand", "continent": "Australia" },
    { "value": "NI", "text": "Nicaragua", "continent": "North America" },
    { "value": "NE", "text": "Niger", "continent": "Africa" },
    { "value": "NG", "text": "Nigeria", "continent": "Africa" },
    { "value": "NU", "text": "Niue", "continent": "Australia" },
    { "value": "NF", "text": "Norfolk Island", "continent": "Australia" },
    { "value": "MP", "text": "Northern Mariana Islands", "continent": "Australia" },
    { "value": "NO", "text": "Norway", "continent": "Europe" },
    { "value": "OM", "text": "Oman", "continent": "Asia" },
    { "value": "PK", "text": "Pakistan", "continent": "Asia" },
    { "value": "PW", "text": "Palau", "continent": "Australia" },
    { "value": "PS", "text": "Palestine, State of", "continent": "Asia" },
    { "value": "PA", "text": "Panama", "continent": "North America" },
    { "value": "PG", "text": "Papua New Guinea", "continent": "Australia" },
    { "value": "PY", "text": "Paraguay", "continent": "South America" },
    { "value": "PE", "text": "Peru", "continent": "South America" },
    { "value": "PH", "text": "Philippines", "continent": "Asia" },
    { "value": "PN", "text": "Pitcairn", "continent": "Australia" },
    { "value": "PL", "text": "Poland", "continent": "Europe" },
    { "value": "PT", "text": "Portugal", "continent": "Europe" },
    { "value": "PR", "text": "Puerto Rico", "continent": "North America" },
    { "value": "QA", "text": "Qatar", "continent": "Asia" },
    { "value": "RO", "text": "Romania", "continent": "Europe" },
    { "value": "RU", "text": "Russian Federation", "continent": "Europe" },
    { "value": "RW", "text": "Rwanda", "continent": "Africa" },
    { "value": "RE", "text": "Réunion", "continent": "Africa" },
    { "value": "BL", "text": "Saint Barthélemy", "continent": "North America" },
    { "value": "SH", "text": "Saint Helena", "continent": "Africa" },
    { "value": "KN", "text": "Saint Kitts And Nevis", "continent": "North America" },
    { "value": "LC", "text": "Saint Lucia", "continent": "North America" },
    { "value": "MF", "text": "Saint Martin", "continent": "North America" },
    { "value": "PM", "text": "Saint Pierre And Miquelon", "continent": "North America" },
    { "value": "VC", "text": "Saint Vincent And The Grenedines", "continent": "North America" },
    { "value": "WS", "text": "Samoa", "continent": "Australia" },
    { "value": "SM", "text": "San Marino", "continent": "Europe" },
    { "value": "ST", "text": "Sao Tome and Principe", "continent": "Africa" },
    { "value": "SA", "text": "Saudi Arabia", "continent": "Asia" },
    { "value": "SN", "text": "Senegal", "continent": "Africa" },
    { "value": "RS", "text": "Serbia", "continent": "Europe" },
    { "value": "SC", "text": "Seychelles", "continent": "Africa" },
    { "value": "SL", "text": "Sierra Leone", "continent": "Africa" },
    { "value": "SG", "text": "Singapore", "continent": "Asia" },
    { "value": "SX", "text": "Sint Maarten", "continent": "North America" },
    { "value": "SK", "text": "Slovakia", "continent": "Europe" },
    { "value": "SI", "text": "Slovenia", "continent": "Europe" },
    { "value": "SB", "text": "Solomon Islands", "continent": "Australia" },
    { "value": "SO", "text": "Somalia", "continent": "Africa" },
    { "value": "ZA", "text": "South Africa", "continent": "Africa" },
    { "value": "GS", "text": "South Georgia and the South Sandwich Islands", "continent": "Antarctica" },
    { "value": "SS", "text": "South Sudan", "continent": "Africa" },
    { "value": "ES", "text": "Spain", "continent": "Europe" },
    { "value": "LK", "text": "Sri Lanka", "continent": "Asia" },
    { "value": "SD", "text": "Sudan", "continent": "Africa" },
    { "value": "SR", "text": "Suriname", "continent": "South America" },
    { "value": "SJ", "text": "Svalbard And Jan Mayen", "continent": "Europe" },
    { "value": "SZ", "text": "Swaziland", "continent": "Africa" },
    { "value": "SE", "text": "Sweden", "continent": "Europe" },
    { "value": "CH", "text": "Switzerland", "continent": "Europe" },
    { "value": "SY", "text": "Syrian Arab Republic", "continent": "Asia" },
    { "value": "TW", "text": "Taiwan, Republic Of China", "continent": "Asia" },
    { "value": "TJ", "text": "Tajikistan", "continent": "Asia" },
    { "value": "TZ", "text": "Tanzania, United Republic of", "continent": "Africa" },
    { "value": "TH", "text": "Thailand", "continent": "Asia" },
    { "value": "TL", "text": "Timor-Leste", "continent": "Asia" },
    { "value": "TG", "text": "Togo", "continent": "Africa" },
    { "value": "TK", "text": "Tokelau", "continent": "Australia" },
    { "value": "TO", "text": "Tonga", "continent": "Australia" },
    { "value": "TT", "text": "Trinidad and Tobago", "continent": "North America" },
    { "value": "TN", "text": "Tunisia", "continent": "Africa" },
    { "value": "TR", "text": "Turkey", "continent": "Europe" },
    { "value": "TM", "text": "Turkmenistan", "continent": "Asia" },
    { "value": "TC", "text": "Turks and Caicos Islands", "continent": "North America" },
    { "value": "TV", "text": "Tuvalu", "continent": "Australia" },
    { "value": "UG", "text": "Uganda", "continent": "Africa" },
    { "value": "UA", "text": "Ukraine", "continent": "Europe" },
    { "value": "AE", "text": "United Arab Emirates", "continent": "Asia" },
    { "value": "GB", "text": "United Kingdom", "continent": "Europe" },
    { "value": "US", "text": "United States", "continent": "North America" },
    { "value": "UM", "text": "United States Minor Outlying Islands", "continent": "Australia" },
    { "value": "UY", "text": "Uruguay", "continent": "South America" },
    { "value": "UZ", "text": "Uzbekistan", "continent": "Asia" },
    { "value": "VU", "text": "Vanuatu", "continent": "Australia" },
    { "value": "VE", "text": "Venezuela, Bolivarian Republic of", "continent": "South America" },
    { "value": "VN", "text": "Vietnam", "continent": "Asia" },
    { "value": "VG", "text": "Virgin Islands, British", "continent": "North America" },
    { "value": "VI", "text": "Virgin Islands, U.S.", "continent": "North America" },
    { "value": "WF", "text": "Wallis and Futuna", "continent": "Australia" },
    { "value": "EH", "text": "Western Sahara", "continent": "Africa" },
    { "value": "YE", "text": "Yemen", "continent": "Asia" },
    { "value": "ZM", "text": "Zambia", "continent": "Africa" },
    { "value": "ZW", "text": "Zimbabwe", "continent": "Africa" },
]
