export default [
    { "value": 0, "text": "Select Interest" },
    { "value": 1, "item": "abortion_and_family_planning", "text": "Abortion and Family Planning", "group_ids": "1" },
    { "value": 2, "item": "advocacy_and_civil_human_rights", "text": "Advocacy and Civil / Human Rights", "group_ids": "3,1" },
    { "value": 3, "item": "african_american", "text": "African-American", "group_ids": "3,1" },
    { "value": 4, "item": "agriculture", "text": "Agriculture", "group_ids": "4,2" },
    { "value": 5, "item": "aids_hiv", "text": "AIDS/HIV", "group_ids": "1" },
    { "value": 6, "item": "american_indian", "text": "American-Indian", "group_ids": "8" },
    { "value": 7, "item": "animal_rights_welfare_and_services", "text": "Animal Rights, Welfare, and Services", "group_ids": "5,1" },
    { "value": 8, "item": "animals", "text": "Animals", "group_ids": "5,1" },
    { "value": 9, "item": "arts_culture_humanities", "text": "Arts, Culture, Humanities", "group_ids": "8" },
    { "value": 10, "item": "asian_american", "text": "Asian-American", "group_ids": "3" },
    { "value": 11, "item": "blind_and_visually_impaired", "text": "Blind and Visually-Impaired", "group_ids": "1" },
    { "value": 12, "item": "board_development", "text": "Board Development", "group_ids": "3,1" },
    { "value": 13, "item": "botanical_gardens_parks_and_nature_centers", "text": "Botanical Gardens, Parks, and Nature Centers", "group_ids": "4,2" },
    { "value": 14, "item": "cancer", "text": "Cancer", "group_ids": "1" },
    { "value": 15, "item": "child_protection_and_family_services_children_and_youth", "text": "Child Protection and Family Services (Children and Youth)", "group_ids": "6" },
    { "value": 16, "item": "civic_engagement_and_advocacy", "text": "Civic Engagement and Advocacy", "group_ids": "3,1" },
    { "value": 17, "item": "climate_change", "text": "Climate Change", "group_ids": "4,2" },
    { "value": 18, "item": "community_and_housing_development", "text": "Organization and Housing Development", "group_ids": "3,1" },
    { "value": 19, "item": "community_foundations", "text": "Organization Foundations", "group_ids": "3,1" },
    { "value": 20, "item": "computers_and_technology", "text": "Computers and Technology", "group_ids": "3,1" },
    { "value": 21, "item": "consumer_protection_and_legal_aid", "text": "Consumer Protection and Legal Aid", "group_ids": "3,1" },
    { "value": 22, "item": "crime_and_fire_prevention", "text": "Crime and Fire Prevention", "group_ids": "3,1" },
    { "value": 23, "item": "crisis_support", "text": "Crisis Support", "group_ids": "4,2" },
    { "value": 24, "item": "disabled", "text": "Disabled", "group_ids": "1" },
    { "value": 25, "item": "disaster_relief", "text": "Disaster Relief", "group_ids": "3,1" },
    { "value": 26, "item": "diseases_disorders_and_disciplines", "text": "Diseases, Disorders, and Disciplines", "group_ids": "1" },
    { "value": 27, "item": "drug_and_alcohol_abuse", "text": "Drug and Alcohol Abuse", "group_ids": "1" },
    { "value": 28, "item": "education", "text": "Education", "group_ids": "2" },
    { "value": 29, "item": "emergency_and_safety", "text": "Emergency and Safety", "group_ids": "4,2" },
    { "value": 30, "item": "employment", "text": "Employment", "group_ids": "3,1" },
    { "value": 31, "item": "environment", "text": "Environment", "group_ids": "4,2" },
    { "value": 32, "item": "environmental_protection_and_conservation", "text": "Environmental Protection and Conservation", "group_ids": "4,2" },
    { "value": 33, "item": "food_banks_food_pantries_and_food_distribution", "text": "Food Banks, Food Pantries, and Food Distribution", "group_ids": "3,1" },
    { "value": 34, "item": "fundraising_organizations", "text": "Fundraising Organizations", "group_ids": "3,1" },
    { "value": 35, "item": "gun_control_pro_con", "text": "Gun Control (Pro/Con)", "group_ids": "3,1" },
    { "value": 36, "item": "health_general_water", "text": "Health - General (Water)", "group_ids": "1" },
    { "value": 37, "item": "health_and_medicine", "text": "Health and Medicine", "group_ids": "1" },
    { "value": 38, "item": "hispanic", "text": "Hispanic", "group_ids": "8" },
    { "value": 39, "item": "homeless_and_housing_services", "text": "Homeless and Housing Services", "group_ids": "3,1" },
    { "value": 40, "item": "human_rights", "text": "Human Rights", "group_ids": "3,1" },
    { "value": 41, "item": "human_services", "text": "Human Services", "group_ids": "1" },
    { "value": 42, "item": "humanitarian_relief_supplies", "text": "Humanitarian Relief Supplies", "group_ids": "1" },
    { "value": 43, "item": "hunger", "text": "Hunger", "group_ids": "1" },
    { "value": 44, "item": "immigrants_and_refugees", "text": "Immigrants and Refugees", "group_ids": "1" },
    { "value": 45, "item": "international_development_and_relief_services", "text": "International Development and Relief Services", "group_ids": "1" },
    { "value": 46, "item": "international_justice_and_legal", "text": "International Justice and Legal", "group_ids": "3,1" },
    { "value": 47, "item": "international_peace_security_and_affairs", "text": "International Peace, Security, and Affairs", "group_ids": "3,1" },
    { "value": 48, "item": "jewish_and_israel", "text": "Jewish and Israel", "group_ids": "8" },
    { "value": 49, "item": "lgbt", "text": "LGBT", "group_ids": "3,1" },
    { "value": 50, "item": "libraries_historical_societies_and_landmark_preservation", "text": "Libraries, Historical Societies and Landmark Preservation", "group_ids": "4,2" },
    { "value": 51, "item": "literacy", "text": "Literacy", "group_ids": "2" },
    { "value": 52, "item": "malaria", "text": "Malaria", "group_ids": "1" },
    { "value": 53, "item": "maternal_health", "text": "Maternal Health", "group_ids": "1" },
    { "value": 54, "item": "medical_research", "text": "Medical Research", "group_ids": "1" },
    { "value": 55, "item": "mental_health_and_disabilities", "text": "Mental Health and Disabilities", "group_ids": "1" },
    { "value": 56, "item": "mentorship", "text": "Mentorship", "group_ids": "2" },
    { "value": 57, "item": "multipurpose_human_service_organizations", "text": "Multipurpose Human Service Organizations", "group_ids": "3,1" },
    { "value": 58, "item": "museums", "text": "Museums", "group_ids": "2" },
    { "value": 59, "item": "other_education_programs_and_services", "text": "Other Education Programs and Services", "group_ids": "2" },
    { "value": 60, "item": "performing_arts", "text": "Performing Arts", "group_ids": "8" },
    { "value": 61, "item": "politics", "text": "Politics", "group_ids": "3,1" },
    { "value": 62, "item": "population_planning", "text": "Population Planning", "group_ids": "4,2" },
    { "value": 63, "item": "private_elementary_and_secondary_schools", "text": "Private Elementary and Secondary Schools", "group_ids": "2" },
    { "value": 64, "item": "private_liberal_arts_colleges", "text": "Private Liberal Arts Colleges", "group_ids": "2" },
    { "value": 65, "item": "public_benefit", "text": "Public Benefit", "group_ids": "3,1" },
    { "value": 66, "item": "public_broadcasting_and_media", "text": "Public Broadcasting and Media", "group_ids": "3,1" },
    { "value": 67, "item": "public_policy", "text": "Public Policy", "group_ids": "3,1" },
    { "value": 68, "item": "race_and_ethnicity", "text": "Race and Ethnicity", "group_ids": "3,1" },
    { "value": 69, "item": "religion_faith_based", "text": "Religion, Faith Based", "group_ids": "7" },
    { "value": 70, "item": "religious_activities", "text": "Religious Activities", "group_ids": "7" },
    { "value": 71, "item": "religious_media_and_broadcasting", "text": "Religious Media and Broadcasting", "group_ids": "7" },
    { "value": 72, "item": "research_and_public_policy_institutions", "text": "Research and Public Policy Institutions", "group_ids": "3,1" },
    { "value": 73, "item": "seniors", "text": "Seniors", "group_ids": "3,1" },
    { "value": 74, "item": "single_country_support_organizations", "text": "Single Country Support Organizations", "group_ids": "3,1" },
    { "value": 75, "item": "social_services", "text": "Social Services", "group_ids": "3,1" },
    { "value": 76, "item": "sports_and_recreation", "text": "Sports and Recreation", "group_ids": "1" },
    { "value": 77, "item": "terminally_or_chronically_ill", "text": "Terminally or Chronically Ill", "group_ids": "1" },
    { "value": 78, "item": "travel_and_transportation", "text": "Travel and Transportation", "group_ids": "3,1" },
    { "value": 79, "item": "treatment_and_prevention_services", "text": "Treatment and Prevention Services", "group_ids": "3,1" },
    { "value": 80, "item": "universities_graduate_schools_and_technological_institutes", "text": "Universities, Graduate Schools, and Technological Institutes", "group_ids": "2" },
    { "value": 81, "item": "veterans_and_military_families", "text": "Veterans and Military Families", "group_ids": "3,1" },
    { "value": 82, "item": "water_issues", "text": "Water Issues", "group_ids": "4,2" },
    { "value": 83, "item": "wildlife_conservation", "text": "Wildlife Conservation", "group_ids": "4,2" },
    { "value": 84, "item": "women_s_rights", "text": "Women's Rights", "group_ids": "3,1" },
    { "value": 85, "item": "youth_development", "text": "Youth Development", "group_ids": "6" },
    { "value": 86, "item": "zoos_and_aquariums", "text": "Zoos and Aquariums", "group_ids": "4,2" }
]
